import {
    Container,
    Heading,
    Text,
    ListItem,
    Link,
    Image,
    UnorderedList,
    OrderedList,
    VStack,
} from '@chakra-ui/react';

const CouponComponent = () => {
    return (
        <Container maxW="container.md" py={5}>
            <VStack spacing={4} align="left">
                <Heading as="h1" size="xl">Coupon</Heading>
                <Text fontSize="lg">
                    Using coupons in your subscription-based business can attract new customers, increase their loyalty,
                    and
                    drive sales. Use coupons to offer discounts on your subscription plans. In addition, you can
                    generate
                    special codes that your customers can apply to get a discount on their subscription.
                </Text>

                <Text as="div">
                    This feature is intended for recurring billing and subscription services only. It does not apply to
                    one-time purchases due to the lack of trial periods for such purchases.
                </Text>

                <Text>
                    With coupons and their codes, you can:
                    <UnorderedList>
                        <ListItem>Apply discounts to all invoices (note that invoices automatically generated by a
                            subscription
                            are records that detail the amounts owed to customers and track the status of payments from
                            draft to finalization), a single invoice, or for a predefined period.
                        </ListItem>
                        <ListItem>Reduce the total amount of an invoice by a fixed amount or a certain
                            percentage.</ListItem>
                    </UnorderedList>
                </Text>

                <Text as="div">
                    Additionally, you can set up coupons that need to be redeemed by a certain date or have a maximum
                    redemption limit for all customers.
                </Text>

                <Text as="div">
                    This feature is not enabled by default currently, so please contact <Link
                    href="https://support.solidgate.com/support/tickets/new" color="teal.500"
                    isExternal>Solidgate</Link> to activate it.
                </Text>

                <Text>
                    To facilitate customer savings and promote sales, coupons can be converted into discounts during the
                    payment process.
                </Text>

                <Text as="div">
                    The following sections serve as a guide that walks you through the comprehensive management of
                    coupons,
                    including their creation, customization, and tracking. You learn how to set parameters like discount
                    type, duration, redemption limits, and expiration dates, all of which are crucial for executing
                    effective promotional strategies.
                </Text>

                <Heading as="h2" size="lg">Create coupon</Heading>

                <Text>
                    To create coupons in the HUB
                    <OrderedList>
                        <ListItem>On the <strong>subscription</strong> tab, open the <strong>Products (new
                            Hub)</strong> section.</ListItem>
                        <ListItem>Open the <strong>Coupons</strong> page.</ListItem>
                        <ListItem>Click <strong>+ Create coupon</strong>.</ListItem>
                        <ListItem>Provide the coupon information, including the coupon parameters.</ListItem>
                        <ListItem>Click <strong>Create coupon</strong>.</ListItem>
                    </OrderedList>
                </Text>

                <Heading as="h2" size="lg">Delete coupon</Heading>

                <Text>
                    When deleting a coupon, there are certain limitations and considerations to keep in mind:
                    <UnorderedList>
                        <ListItem><strong>No Redemptions</strong> <br/> The coupon can be freely deleted when it has not
                            been
                            redeemed by any customer.
                        </ListItem>
                        <ListItem><strong>Irreversible action</strong> <br/> Once a coupon is deleted, it is removed
                            from the
                            coupon listing and cannot be restored. This makes it unavailable for any future uses.
                            Additionally, deleting a coupon also removes all its associated coupon codes.
                        </ListItem>
                    </UnorderedList>
                </Text>

                <Heading as="h2" size="lg">Archive coupon</Heading>

                <Text>
                    If a coupon has been redeemed one or more times, the only option available is to archive it, rather
                    than
                    delete it.
                    <UnorderedList>
                        <ListItem><strong>Visibility</strong> <br/> An archived coupon remains visible in the coupon
                            listing for
                            record-keeping purposes.
                        </ListItem>
                        <ListItem><strong>Immutability</strong> <br/> Once archived, no further actions or modifications
                            can be
                            performed on the coupon. It becomes a read-only item in your system. Archiving a coupon also
                            archives all its associated coupon codes.
                        </ListItem>
                    </UnorderedList>
                </Text>

                <Heading as="h2" size="lg">Coupon statuses</Heading>

                <Text>
                    Coupon statuses provide valuable insights into the state of each coupon created. They serve as a
                    vital
                    tool for streamlining discount management and enhancing the effectiveness of promotional strategies.
                </Text>

                <Image src="https://cdn.solidgate.com/sl-guides/sbs_cp_1.0.png" alt="Coupon statuses" boxSize="100%"/>

                <Heading as="h2" size="lg">Discount usage</Heading>

                <Text as="div">
                    The <strong>predefined</strong> and the <strong>direct</strong> flows are the primary ways to apply
                    discounts to customer subscriptions.
                </Text>

            </VStack>
        </Container>
    );
};

export default CouponComponent;
